### ISSUE TITLE
Returning the response even if Warden interrupts

### ISSUE THREAD

**Issue by franzliedke** [ajsharp/warden-rspec-rails#4]
See [this line](https://github.com/ajsharp/warden-rspec-rails/blob/d44e129423465a34906a4a881081a702c53d2239/lib/warden/test/controller_helpers.rb#L17).

What is the rationale behind this? I want to test certain authentication checks in my controller specs, but this behavior throws me off, because the controller code after my `warden.authenticate!` calls fails if it is executed without a valid user (which it does not expect due to that guard statement).

**Comment by ajsharp** [comment]
Frankly, I have no idea :) I wrote this thing so long ago, and it's been so long since I used it, I'm afraid I can't be of much help in this area. Feel free to change it in a PR if it makes sense to you though.

**Comment by franzliedke** [comment]
Never mind, looks like I misunderstood it.

Everything is finally working as expected. :)
