### ISSUE TITLE
incompatible with Ruby 3.0.0

### ISSUE THREAD

**Issue by mwmeyer** [ajsharp/warden-rspec-rails#7]
I'm not sure whether this gem is maintained, but it was raising an error for me recently when attempting to ruby 3.0.

The `process(*)` method here needs to change to `process(*, **)` to account for ruby 3 arg syntax changes:
https://github.com/ajsharp/warden-rspec-rails/blob/master/lib/warden/test/controller_helpers.rb#L16
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

This is an issue similar to:
https://github.com/rails/rails-controller-testing/issues/69

**Comment by BrianHawley** [comment]
@ajsharp #9 fixes this one too.
